[context.production]
command = "npm run build"
publish = "dist"
branch = "main"

[context.deploy-preview]
command = "npm run build"
publish = "dist"

[context.staging]
command = "npm run build"
publish = "dist"
branch = "develop"